### PR TITLE
Add DTS bug reporting template

### PR DESCRIPTION
**Pull request by DaniilKl**

### CODE REVIEW

**Review by macpijan — COMMENTED** [review]
If this is the only diff between the existing template and the new one:

```
diff dts_bug_report.yml bug_report.yml 
1c1
< 
---
> name: Bug report
3,5c3
< labels:
<   - ["bug"]
<   - ["DasharoToolsSuite"]
---
> labels: ["bug"]
16c14
<       description: The model of device you're using DTS on.
---
>       description: The model of device you're using Dasharo on.
18c16
<       required: false
---
>       required: true
23,24c21,22
<       label: DTS version
<       description: The version of DTS you're using (e.g., `v0.2.0` or commit if you have built DTS manually)
---
>       label: Dasharo version
>       description: The version of Dasharo you're using (e.g., `v0.2.0`), or coreboot and edk2 commit hashes if built from an untagged revision
32c30
<       description: The component or functionality of DTS that is not working as expected.
---
>       description: The component or functionality of Dasharo that is not working as expected.
```

I worry about the DRY strategy. The issue syntax is quite extensive: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
I would like at least confirmation that it has been reviewed and there is no easy way to stick with a single bug report, allowing for some selection or drop down list selecting platforms, or components, or in other ways reusing the common parts.

**Comment by DaniilKl** [comment]
@macpijan, could not dissagree with you. I think that staying with one bug template is the best solution here, but I do not agree with the idea of using additional graphical solutions e.g. drop down list that will complicate the process of composing of an issue. I think making bug template description more generic will be just fine. 
Check commit 74ef199168cd96ae05ae6bbb8ecfc0d67ff36966.

**Comment by DaniilKl** [comment]
> Is there a way of assigning a label, like DasharoToolsSuite, or protectli_vault_cml based on which product/platform is selected by a user?
GitHub issue template is created using [syntax for GitHub form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema) and there is no such functionality available.

**Comment by macpijan** [comment]
@DaniilKl I have managed to do this with additional GH workflow here: https://github.com/Dasharo/dasharo-issues/commit/3a3912699b80b9cf8f6ef8cb116d16480f814f1f

**Comment by macpijan** [comment]
Google search. Documented results here: https://github.com/orgs/community/discussions/44350#discussioncomment-8919921

**Pull request merged**
